name: CI
on:
  workflow_dispatch:
  schedule:
    - cron: 20 4 * * 6

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Run get.sh 
        id: sh
        run: |
          sudo chmod +x get.sh
          source get.sh
          echo -e "- Tor version: $TOR_VER\n- [Extracted from official Tor website](torproject.org)\n- Orbot version: $ORBOT_VER\n- [Extracted from official Orbot repo](github.com/guardianproject/orbot)\n - FileHostings:\n    - [fotolub.com/$F_KEY](fotolub.com/$F_KEY)" > release_body.txt
          echo "tor_ver=$TOR_VER" >> $GITHUB_OUTPUT
          echo "orbot_ver=$ORBOT_VER" >> $GITHUB_OUTPUT
          echo "ver=tor-$TOR_VER---orbot-$ORBOT_VER" >> $GITHUB_OUTPUT

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2.0.5
        with:
          name: ${{ steps.sh.outputs.ver }}
          tag_name: ${{ steps.sh.outputs.ver }}
          body_path: release_body.txt
          files: downloads/*
